<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphToMany;

class Tag extends Model
{
    use HasFactory;

    protected $fillable = ['tag_name'];


    /**
     * Get all of the articles that are assigned this tag.
     */
    public function articles(): MorphToMany
    {
        return $this->morphedByMany(Article::class, 'taggable');
    }

    public function getRouteKeyName()
    {
        return 'tag_name'; // TODO: Change the autogenerated stub
    }
}
